// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/30/2025, 5:37:12 PM
const configMerger = require("/Users/hannes/Documents/programming/better-callouts-docs/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/hannes/Documents/programming/better-callouts-docs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hannes/Documents/programming/better-callouts-docs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hannes/Documents/programming/better-callouts-docs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hannes/Documents/programming/better-callouts-docs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hannes/Documents/programming/better-callouts-docs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hannes/Documents/programming/better-callouts-docs/plugins/**/*.{js,ts,mjs}","/Users/hannes/Documents/programming/better-callouts-docs/composables/**/*.{js,ts,mjs}","/Users/hannes/Documents/programming/better-callouts-docs/utils/**/*.{js,ts,mjs}","/Users/hannes/Documents/programming/better-callouts-docs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hannes/Documents/programming/better-callouts-docs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hannes/Documents/programming/better-callouts-docs/app.config.{js,ts,mjs}"] }));

module.exports = config
